### PR TITLE
Replace/Default actually occur before/after Provide now

### LINKED ISSUE #62: Module.replace() doesn’t work correctly
Works: 

```
replace(’template’, …)
```
Does not work:
```
replace().template(…)
```

### PR DESCRIPTION
**Pull request by loppear**
Resolves #62

### CODE REVIEW

File: src/Dispatcher.js [hunk 1]
```diff
@@ -129,7 +129,7 @@ export default class Dispatcher extends EventEmitter {
           results = []
         }
         return this._squashArrayResults(Promise.reduce(super.listeners(event+".after"), waterfaller(newArgs), results));
-      });
+      })
```
Comment (mjreich) [inline src/Dispatcher.js]: Don’t like semicolons? ;)

**Comment by mjreich** [comment]
:+1:

**Comment by mjreich** [comment]
Closes #62
